[package]
name = "hypercore-protocol"
version = "0.0.1"
license = "MIT OR Apache-2.0"
description = "Replication protocol for Hypercore feeds"
authors = ["Franz Heinzmann (Frando) <frando@unbiskant.org>"]
documentation = "https://docs.rs/hypercore-protocol"
repository = "https://github.com/Frando/hypercore-protocol-rs"
readme = "README.md"
edition = "2018"
keywords = ["dat", "p2p", "stream", "feed", "hypercore", "protocol"]
categories = [
  "asynchronous",
  "concurrency",
  "cryptography",
  "data-structures",
  "encoding",
]

[lib]
# benchmarks are using criterion
bench = false

[dependencies]
futures = "0.3"
snow = { git = "https://github.com/mcginty/snow.git", branch = "master", features = ["risky-raw-split", "xchachapoly"] }
prost = "0.6"
bytes = "0.5"
varinteger = "1.0"
rand = "0.7"
blake2-rfc = "0.2"
hex = "0.4"
async-trait = "0.1"
salsa20 = "0.4"
log = "0.4"
pretty-hash = "0.4"
futures-timer = "3.0"
instant = "0.1"
getrandom = "0.1"

[dev-dependencies]
async-std = "1.5"
env_logger = "0.7.1"
hypercore = { git = "https://github.com/Frando/datrs-hypercore", branch = "protocol-dev" }
random-access-disk = "2.0.0"
random-access-memory = "2.0.0"
random-access-storage = "4.0.0"
anyhow = "1.0.28"
criterion = "0.3.2"
pretty-bytes = "0.2.2"

[build-dependencies]
prost-build = "0.6.1"

[features]
wasm-bindgen = [
  "instant/wasm-bindgen", 
  "getrandom/wasm-bindgen", 
  "futures-timer/wasm-bindgen"
]

[profile.bench]
debug = true

[[bench]]
name = "throughput"
harness = false
